
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '8E5D2CBD60F8DDE9370978F9BAD7F2E4'
    
_lr_action_items = {'RP':([1,2,5,7,8,19,20,21,22,23,24,25,26,27,28,],[-9,-2,7,-1,-8,24,25,26,27,28,-7,-4,-3,-5,-6,]),'POW':([7,],[9,]),'NUMBER':([0,3,6,14,15,16,17,18,],[1,1,8,1,1,1,1,1,]),'MINUS':([7,],[10,]),'PLUS':([7,],[11,]),'LP':([0,3,9,10,11,12,13,14,15,16,17,18,],[3,3,14,15,16,17,18,3,3,3,3,3,]),'SC':([1,2,4,5,7,8,19,20,21,22,23,24,25,26,27,28,],[-9,-2,6,6,-1,-8,6,6,6,6,6,-7,-4,-3,-5,-6,]),'MUL':([7,],[12,]),'DIV':([7,],[13,]),'ID':([0,3,14,15,16,17,18,],[2,2,2,2,2,2,2,]),'$end':([1,2,4,7,8,24,25,26,27,28,],[-9,-2,0,-1,-8,-7,-4,-3,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'e':([0,3,14,15,16,17,18,],[4,5,19,20,21,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> e","S'",1,None,None,None),
  ('e -> LP e RP','e',3,'p_b','equationLY.py',33),
  ('e -> ID','e',1,'p_id','equationLY.py',37),
  ('e -> LP e RP PLUS LP e RP','e',7,'p_exp','equationLY.py',41),
  ('e -> LP e RP MINUS LP e RP','e',7,'p_exp','equationLY.py',42),
  ('e -> LP e RP MUL LP e RP','e',7,'p_exp','equationLY.py',43),
  ('e -> LP e RP DIV LP e RP','e',7,'p_exp','equationLY.py',44),
  ('e -> LP e RP POW LP e RP','e',7,'p_exp','equationLY.py',45),
  ('e -> e SC NUMBER','e',3,'p_val','equationLY.py',50),
  ('e -> NUMBER','e',1,'p_number','equationLY.py',54),
]
