
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '99DD974D52E0A2218EBA47F5458DD152'
    
_lr_action_items = {'RP':([1,2,3,6,7,18,19,20,21,22,23,24,25,26,27,],[-3,-9,-2,7,-1,23,24,25,26,27,-4,-7,-6,-5,-8,]),'POW':([7,],[8,]),'IMAG':([0,4,14,15,16,17,],[1,1,1,1,1,1,]),'NUMBER':([0,4,13,14,15,16,17,],[2,2,18,2,2,2,2,]),'COMPLEX':([0,4,14,15,16,17,],[3,3,3,3,3,3,]),'PLUS':([7,],[9,]),'LP':([0,4,8,9,10,11,12,14,15,16,17,],[4,4,13,14,15,16,17,4,4,4,4,]),'MUL':([7,],[10,]),'DIV':([7,],[11,]),'MINUS':([7,],[12,]),'$end':([1,2,3,5,7,23,24,25,26,27,],[-3,-9,-2,0,-1,-4,-7,-6,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'e':([0,4,14,15,16,17,],[5,6,19,20,21,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> e","S'",1,None,None,None),
  ('e -> LP e RP','e',3,'p_b','complexLY.py',41),
  ('e -> COMPLEX','e',1,'p_complex','complexLY.py',45),
  ('e -> IMAG','e',1,'p_imag','complexLY.py',65),
  ('e -> LP e RP POW LP NUMBER RP','e',7,'p_expr','complexLY.py',72),
  ('e -> LP e RP DIV LP e RP','e',7,'p_expr','complexLY.py',73),
  ('e -> LP e RP MUL LP e RP','e',7,'p_expr','complexLY.py',74),
  ('e -> LP e RP PLUS LP e RP','e',7,'p_expr','complexLY.py',75),
  ('e -> LP e RP MINUS LP e RP','e',7,'p_expr','complexLY.py',76),
  ('e -> NUMBER','e',1,'p_number','complexLY.py',90),
]
